---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.1
    commands:
      - php -v
      - composer update
      - composer require phpstan/phpstan
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/ bin/ www/

  - name: phpstan
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - vendor/bin/phpstan analyse src
    failure: ignore

  - name: phploc
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - phploc src
    failure: ignore

  - name: deployment
    image: appleboy/drone-ssh
    depends_on:
      - phpcs
    settings:
      host:
        from_secret: framework_host
      username:
        from_secret: framework_username
      password:
        from_secret: framework_password
      port: 22
      script:
        - cd /home/fwjoomla/siteData
        - bin/framework update:server
    when:
      branch:
        - master
      status:
        - success
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 2215efab7624c713f07192802222fa7d5fa0ad041fc3a3af3c8bbf591e9b629d

...
