---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.1
    commands:
      - php -v
      - composer update
      - composer require phpmd/phpmd phpstan/phpstan
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/ bin/ www/

  - name: phpmd
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - vendor/bin/phpmd src text cleancode
      - vendor/bin/phpmd src text codesize
      - vendor/bin/phpmd src text controversial
      - vendor/bin/phpmd src text design
      - vendor/bin/phpmd src text unusedcode
    failure: ignore

  - name: phpstan
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - vendor/bin/phpstan analyse src
    failure: ignore

  - name: phploc
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - phploc src
    failure: ignore

  - name: phpcpd
    image: joomlaprojects/docker-images:php8.1
    depends_on:
      - composer
    commands:
      - phpcpd src
    failure: ignore

  - name: deployment
    image: appleboy/drone-ssh
    depends_on:
      - phpcs
    settings:
      host:
        from_secret: framework_host
      username:
        from_secret: framework_username
      password:
        from_secret: framework_password
      port: 22
      script:
        - cd /home/fwjoomla/siteData
        - bin/framework update:server
    when:
      branch:
        - master
      status:
        - success
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 3976132d114c361d6cd7b0429b51b729adcea4f1065ccba4e589889cad94ae12

...
