<?php
/**
 * Joomla! Framework Website
 *
 * @copyright  Copyright (C) 2014 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license    http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License Version 2 or Later
 */

namespace Joomla\FrameworkWebsite\Command\Router;

use Joomla\Application\AbstractApplication;
use Joomla\Controller\AbstractController;
use Joomla\FrameworkWebsite\CommandInterface;
use Joomla\Input\Input;
use Joomla\Router\Router;

/**
 * Router cache command
 *
 * @method         \Joomla\FrameworkWebsite\CliApplication  getApplication()  Get the application object.
 * @property-read  \Joomla\FrameworkWebsite\CliApplication  $app              Application object
 *
 * @since          1.0
 */
class CacheCommand extends AbstractController implements CommandInterface
{
	/**
	 * The application router
	 *
	 * @var    Router
	 * @since  1.0
	 */
	private $router;

	/**
	 * Instantiate the controller.
	 *
	 * @param   Router               $router  The application router.
	 * @param   Input                $input   The input object.
	 * @param   AbstractApplication  $app     The application object.
	 *
	 * @since   1.0
	 */
	public function __construct(Router $router, Input $input = null, AbstractApplication $app = null)
	{
		parent::__construct($input, $app);

		$this->router = $router;
	}

	/**
	 * Execute the controller.
	 *
	 * @return  boolean
	 *
	 * @since   1.0
	 * @throws  \RuntimeException
	 */
	public function execute()
	{
		$this->getApplication()->outputTitle('Cache Router');

		// Check if caching is enabled
		$twigCache = $this->getApplication()->get('router.cache', false);

		if ($twigCache === false)
		{
			$this->getApplication()->out('<info>Router caching is disabled.</info>');

			return true;
		}

		$this->getApplication()->out('<info>Resetting Router Cache</info>');

		file_put_contents(JPATH_ROOT . '/cache/CompiledRouter.php', $this->compileRouter());

		$this->getApplication()->out('<info>The router has been cached.</info>');

		return true;
	}

	/**
	 * Get the command's description
	 *
	 * @return  string
	 *
	 * @since   1.0
	 */
	public function getDescription() : string
	{
		return 'Resets the router cache.';
	}

	/**
	 * Get the command's title
	 *
	 * @return  string
	 *
	 * @since   1.0
	 */
	public function getTitle() : string
	{
		return 'Reset Router Cache';
	}

	/**
	 * Compile the router into a PHP file
	 *
	 * @return  string
	 *
	 * @since   1.0
	 */
	private function compileRouter() : string
	{
		// Make the routes data available for the compiled router
		$refl = new \ReflectionClass($this->router);

		$routesProperty = $refl->getProperty('routes');
		$routesProperty->setAccessible(true);

		$routeData = $routesProperty->getValue($this->router);

		$router = <<<PHP
<?php

/**
 * Compiled application router, this file is auto-generated by the `router:cache` command.
 */
class CompiledRouter extends Joomla\Router\Router
{
	protected \$routes = [

PHP;

		foreach ($routeData as $method => $routes)
		{
			$router .= "\t\t'$method' => [\n";

			foreach ($routes as $route)
			{
				$router .= "\t\t\t" . $this->formatValue($route) . ",\n";
			}

			$router .= "\t\t],\n";
		}

		$router .= <<<PHP
	];
}

PHP;
		return $router;
	}


	/**
	 * Format a value for the string conversion
	 *
	 * @param   mixed  $value  The value to format
	 *
	 * @return  mixed  The formatted value
	 *
	 * @since   __DEPLOY_VERSION__
	 */
	private function formatValue($value)
	{
		switch (gettype($value))
		{
			case 'string':
				return "'" . addcslashes($value, '\\\'') . "'";

			case 'array':
			case 'object':
				return $this->getArrayString((array) $value);

			case 'double':
			case 'integer':
				return $value;

			case 'boolean':
				return $value ? 'true' : 'false';
		}
	}

	/**
	 * Method to get an array as an exported string.
	 *
	 * @param   array  $a  The array to get as a string.
	 *
	 * @return  string
	 *
	 * @since   1.0
	 */
	private function getArrayString(array $a) : string
	{
		$s = '[';
		$i = 0;

		foreach ($a as $k => $v)
		{
			$s .= ($i) ? ', ' : '';
			$s .= "'" . addcslashes($k, '\\\'') . "' => ";
			$s .= $this->formatValue($v);

			$i++;
		}

		$s .= ']';

		return $s;
	}
}
